### ISSUE TITLE
Create presentation for FIMS kickoff

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS-planning#1]
Make presentation for 3/18 FIMS meeting

- [x] Define the key terms (requirements gathering, prioritization, scoping, costing, milestones)
- [x] Identify requirements gathering timeline and steps. Share the requirements template.
- [x] Agenda for next meeting (will use mind mapping to define themes or sub groups that can go off and do requirements gathering)

**Comment by ChristineStawitz-NOAA** [comment]
https://noaa-fims.github.io/FIMS-planning/slides_20210315#1

**Comment by PatrickLynch-NOAA** [comment]
Christine...this looks like it will be a very helpful presentation. I've seen some of this before, but when I've been discussing the SDLC, it's been in the abstract, mostly. So, if most people are like me, this will hammer home what's really being proposed for this project. I'm looking forward to it.

I'm not sure if there are graphics or text that isn't showing...I was prompted to wonder when looking at slide 9, where the only thing that shows under the title is "spreadsheet."

**Comment by Rick-Methot-NOAA** [comment]
let's remind participants to be using their official noaa github handle, not personal github
I think we'll need some structure for the requirements.  It seems too open-ended to simply ask each Center to tell us what they need. 
good to add something about what is already discoverable regarding requirements; e.g. Neil Klaer's R code to extract all features used in a couple 100 SS applications.

**Comment by ChristineStawitz-NOAA** [comment]
- [x] Thanks! I can put in a screenshot of the linked requirements spreadsheet on slide 9
- [x] The link goes to the guidelines for official NOAA github although I need to already get some of our team members to follow the policies better
- [x] One thing that has always been hammered home for me in requirements gathering is a need to start big picture and not constrain brainstorming or lists of requirements. It is much better to get a bunch of requirements we need to deprioritize than have there be hidden requirements that pop up halfway through development. The next phase is an intense scoping/prioritization exercise where we move things out of Phase 1. For this reason, I want the list from centers to be very long
- [x] Can you remind me how to access Neil's code/findings please?

**Comment by Rick-Methot-NOAA** [comment]
I will email you a spreadsheet with Neil's summary.  And try to find his code, which works for SS, ASAP and BAM
Rick
