### ISSUE TITLE
move the requirements doc from your group into the FIMS/Requirements google drive

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS-planning#15]
- [x] [Forecasting](https://docs.google.com/spreadsheets/d/1QvGLwv-LSng56EWPN2hzSWI7J7suIrl9mw8W1GQmaxo/edit?usp=sharing)

**Comment by timjmiller** [comment]
Fitting, Estimation, Simulation has been moved

**Comment by Cole-Monnahan-NOAA** [comment]
@ChristineStawitz-NOAA It was already there.. unless there's another folder or I'm missing something?

**Comment by ChristineStawitz-NOAA** [comment]
I tagged kind of liberally because I couldn't remember who was in which group. Please remove yourself if your groups is in there!
