### ISSUE TITLE
Automated workflow to document code and update web sites

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS-planning#28]

**Comment by Bai-Li-NOAA** [comment]
I suggest that we use following reusable workflows to document R code and update pkgdown sites:

ghactions4r::use_update_roxygen_docs()
ghactions4r::use_pkgdown()

More details about ghactions4r can be found here: [https://github.com/nmfs-fish-tools/ghactions4r](https://github.com/nmfs-fish-tools/ghactions4r)

**Comment by Bai-Li-NOAA** [comment]
Hi @ChristineStawitz-NOAA, I removed myself from the assignees and please feel free to add the workflow leader there. I could not add Kristan there for some reason.

**Comment by ChristineStawitz-NOAA** [comment]
Added the action Bai put in `nmfspalette` to the FIMS repository https://github.com/NOAA-FIMS/FIMS/actions/workflows/update-roxygen.yml
