### ISSUE TITLE
Fill out requirements spreadsheet - AFSC

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS-planning#8]
https://docs.google.com/spreadsheets/d/173ZszPcibwA36hPmscwvLojSrqTkrhWyU2ot5LFax_s/edit#gid=0

**Comment by Cole-Monnahan-NOAA** [comment]
Would be good to tag @JaneSullivan-NOAA for these in the future. We're done for now so closing.

**Comment by JaneSullivan-NOAA** [comment]
> Would be good to tag @JaneSullivan-NOAA for these in the future. We're done for now so closing.

This was my fault actually. I couldn't accept the invite outside of the country because of authentication issues.
